# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0101960ea2b98eb699c6eed52b49378d61809316386cecef7085c239d5c5a7df5a1d8a98f7bdeac85bc2dfff26b7e220b0ecea26327cd829d673ace8429c720e

test:
  secret_key_base: 876be337c7433348901ae20dd14d3eb926d36641fc123e2d02ec3c30f02baeae9181a70bca27eb89927a9c66409330aa69c160502dc96e27de793fe9a561d5bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
